repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        entry: bash -c "cd backend && mypy ."
        args:
          [--config-file=backend/mypy.ini, --install-types, --non-interactive]
        additional_dependencies:
          - django-stubs
          - djangorestframework-stubs
          - sentry_sdk
          - pytest-dotenv
          - unipath
          - djangorestframework
          - djangorestframework-simplejwt
          - django-cors-headers
          - django-filter
          - django_celery_beat
          - sorl-thumbnail
          - channels
          - django-cleanup
          - psycopg2-binary
          - python-magic
          - numpy
          - pandas
          - types-docutils
          - types-Markdown
          - types-psycopg2
          - types-Pygments
          - types-python-dateutil
          - types-pytz
          - types-PyYAML
          - types-requests
          - types-setuptools
          - types-urllib3
  - repo: https://github.com/pycqa/flake8
    rev: '6.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        files: '^backend/.*\.py'
        args: [--config=backend/.flake8]
