name: Automated Testing before Pull Request (PR)

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout branch
      uses: actions/checkout@v2

    # Run tests
    - name: Test backend
      run: |
        pytest tests -s