name: Automated Testing before Pull Request (PR)

on:
  pull_request:
    branches: [ main ]

env:
  AZURE_STORAGE_STRING: ${{ secrets.AZURE_STORAGE_STRING }}
  AMPLO_PLATFORM_STRING: ${{ secrets.AMPLO_PLATFORM_STRING }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checkout branch
    - name: Checkout branch
      uses: actions/checkout@v2

    # Installs dependencies
    - name: Install dependencies
      run : |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    # Run tests
    - name: Test Suite
      run: |
        pytest tests -s
