name: Automated Testing before Pull Request (PR)

on:
  pull_request:
    branches: [main]

env:
  AZURE_STORAGE_STRING: ${{ secrets.AZURE_STORAGE_STRING }}
  AMPLO_PLATFORM_STRING: ${{ secrets.AMPLO_PLATFORM_STRING }}
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # Checkout branch
      - name: Checkout branch
        uses: actions/checkout@v2

      # Set python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install backend dependencies
      - id: python_cache
        uses: actions/cache@v3
        with:
          path: venv
          key: pip-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('**/requirements.txt') }}

      - if: steps.python_cache.outputs.cache-hit != 'true'
        run: |
          # Check if venv exists (restored from secondary keys if any, and delete)
          # You might not need this line if you only have one primary key for the venv caching
          # I kept it in my code as a fail-safe
          if [ -d "venv" ]; then rm -rf venv; fi
          # Re-create the venv
          python3 -m venv venv
          # Install dependencies
          venv/bin/python3 -m pip install -r requirements.txt

      # Run MyPy
      # - name: Run MyPy
      #   run: |
      #     source venv/bin/activate
      #     mypy --install-types --non-interactive .

      # Run Flake8
      - name: Run flake8
        run: |
          source venv/bin/activate
          flake8 .
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      # Checkout branch
      - name: Checkout branch
        uses: actions/checkout@v2

      # Set python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install pipenv
      - name: Install pipenv
        run: |
          pip install --upgrade pip

      # Attach cache
      - id: pip-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('**/requirements.txt') }}

      # Install if necessary
      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-split

      # Run tests
      - name: Test Suite
        run: |
          pytest tests -s --cov --splits 10 --group ${{ matrix.group }}

      # Accumulate codecov
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage${{ matrix.group }}
          path: .coverage

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - name: Run coverage
        run: |
          coverage combine coverage*/.coverage*
          coverage report --fail-under=75
          coverage xml
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          name: amploml-coverage # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
