name: Automated Testing before Pull Request (PR)

on:
  pull_request:
    branches: [ main ]

env:
  AZURE_STORAGE_STRING: ${{ secrets.AZURE_STORAGE_STRING }}
  AMPLO_PLATFORM_STRING: ${{ secrets.AMPLO_PLATFORM_STRING }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checkout branch
    - name: Checkout branch
      uses: actions/checkout@v2

    # Set python version
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    # Installs dependencies
    - name: Install dependencies
      run : |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install pytest-cov

    # Run tests
    - name: Test Suite
      run: |
        pytest tests -s --cov=./ --cov-report=xml
        
    # Code coverage
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        name: amploml-coverage # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
